<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="HMIModificationmarks" nsURI="http://sdq.ipd.kit.edu/HMIModificationmarks"
    nsPrefix="HMIModificationmarks">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractKAMP4HMIModificationRepository"
      abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//HMISeedModifications"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp.model.modificationmarks/model/Modificationmarks.ecore#//AbstractModificationRepository">
      <eTypeArguments eTypeParameter="#//AbstractKAMP4HMIModificationRepository/T"/>
      <eTypeArguments eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp.model.modificationmarks/model/Modificationmarks.ecore#//ChangePropagationStep"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HMISeedModifications" eSuperTypes="../../edu.kit.ipd.sdq.kamp.model.modificationmarks/model/Modificationmarks.ecore#//AbstractSeedModifications"/>
  <eClassifiers xsi:type="ecore:EClass" name="HMIModificationRepository">
    <eGenericSuperTypes eClassifier="#//AbstractKAMP4HMIModificationRepository">
      <eTypeArguments eClassifier="#//HMISeedModifications"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HMIChangePropagationDueToSoftwareDependency"
      eSuperTypes="../../edu.kit.ipd.sdq.kamp.model.modificationmarks/model/Modificationmarks.ecore#//ChangePropagationStep"/>
  <eClassifiers xsi:type="ecore:EClass" name="HMIModifyActorStep">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4hmi.model/model/Kamp4hmiModel.ecore#//ActorStep"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp.model.modificationmarks/model/Modificationmarks.ecore#//AbstractModification">
      <eTypeArguments eTypeParameter="#//HMIModifyActorStep/T"/>
      <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HMIModifySystemStep">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp4hmi.model/model/Kamp4hmiModel.ecore#//SystemStep"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../edu.kit.ipd.sdq.kamp.model.modificationmarks/model/Modificationmarks.ecore#//AbstractModification">
      <eTypeArguments eTypeParameter="#//HMIModifySystemStep/T"/>
      <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
